language: "perl"
perl:
  - "5.30"
  - "5.30-shrplib"
  - "5.28"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
  - "5.10-shrplib"

install:
    - cpanm --notest Module::Install::XSUtil Module::Install::AuthorTests Mojolicious
    - cpanm -v --installdeps --notest .

branches:
  only:
    - master
