language: "perl"
perl:
  - "5.30"
  - "5.30-shrplib"
  - "5.28"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
  - "5.10-shrplib"

install:
    - cpanm --quiet --notest Module::Install::XSUtil Module::Install::AuthorTests
    - cpanm --quiet --installdeps --notest .

    - perl Makefile.PL && make

    - git clone --branch=master https://github.com/kraih/mojo
    # Clone mojo_release to the latest tag
    - git clone --branch="$(git -C mojo tag | tail -1)" mojo/.git mojo_release

script:
    - echo "Testing Mojo::Base::XS standalone"
    - prove --blib --recurse t

    - echo "Testing Mojo::Base::XS with Mojolicious master"
    - HARNESS_PERL_SWITCHES="-Mlib=$TRAVIS_BUILD_DIR/mojo/lib" prove --blib --recurse t

    - echo "Testing Mojo::Base::XS with Mojolicious latest release"
    - HARNESS_PERL_SWITCHES="-Mlib=$TRAVIS_BUILD_DIR/mojo_release/lib" prove --blib --recurse t

    - echo "Testing compatibility with Mojolicious master through Mojolicious test suite"
    - git -C mojo log -1 --oneline
    - HARNESS_PERL_SWITCHES="-Mlib=$TRAVIS_BUILD_DIR/mojo/lib -MMojo::Base::XS=-infect" prove --blib --recurse --QUIET --jobs $(nproc) mojo/t

    - echo "Testing compatibility with Mojolicious latest release"
    - git -C mojo_release tag | tail -1
    - HARNESS_PERL_SWITCHES="-Mlib=$TRAVIS_BUILD_DIR/mojo_release/lib   -MMojo::Base::XS=-infect" prove --blib --recurse --QUIET --jobs $(nproc) mojo_release/t

branches:
  only:
    - master
